### ISSUE TITLE
Patch for /wiki/SampleUsage.wiki

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dnaumenko/java-diff-utils#33]
```
two instead of to
```

Original issue reported on code.google.com by `ort...@symptoma.com` on 16 May 2014 at 10:06

Attachments:
* [SampleUsage.wiki.patch](https://storage.googleapis.com/google-code-attachments/java-diff-utils/issue-33/comment-0/SampleUsage.wiki.patch)

**Comment by dnaumenko** [comment]
Thanks you! 

https://github.com/dnaumenko/java-diff-utils/wiki/Sample-Usage has been updated.
