### ISSUE TITLE
Non-intuitive result when replacing identical letters.

### ISSUE THREAD

**Issue by Tihamer54** [dnaumenko/java-diff-utils#36]
Maybe I'm not understanding what is supposed to be in the Patch object, but I found a way in which the results are a bit squirrely to a naive mind.
My code:
        String original = "aaaaaaaaaa";
        String badCopy =  "aaabaaaaca";
        List<Character> originalList = original.chars().mapToObj(i -> (char) i).collect(Collectors.toList()); 
        List<Character> badCopyList = badCopy.chars().mapToObj(i -> (char) i).collect(Collectors.toList());
        System.out.println("original=" + original);
        System.out.println("badCopy=" + badCopy);
        final Patch<Character> patch = DiffUtils.diff(originalList, badCopyList);
        System.out.println("patch=" + Arrays.toString(patch.getDeltas().toArray()));

The results:
   original=aaaaaaaaaa
   badCopy=aaabaaaaca
   patch2=[[InsertDelta, position: 3, lines: [b]], [InsertDelta, position: 7, lines: [c]], [DeleteDelta, position: 8, lines: [a, a]]]

If I use more varied input strings, the same code results in something that I would expect:
   original=abcdefghijk
   badCopy=abmdefghink
   patch=[[ChangeDelta, position: 2, lines: [c] to [m]], [ChangeDelta, position: 9, lines: [j] to [n]]]

**Comment by dnaumenko** [comment]
The result patch looks good for me. And this one is just comes from how Meyers diff algorithm worked in this particular case.
